title: "Accord: A sane validation library for Scala"
email: "noama@wix.com"
url: "http://wix.github.io/accord"
baseurl: "/accord"

version:
  release: 0.7.3
  snapshot: 0.7.4-SNAPSHOT

markdown: kramdown

gems:
  - jemoji
